---
- name: This playbook install httpd
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
   
  - name: start httpd service
    service: 
      name: http---     # Giving bug intensionally
      state: started 
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
    
  - name: Install apache2 package
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
        
  - name: Start apache2 service
    service: 
      name: apache2
      state: started 
    when: ansible_os_family == "Debian"
    
  - name: copy index.html
    copy: 
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666
