---
- name: setup tomcat
  hosts: all
  become: yes

  tasks:
  - name: Install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz
      dest: /opt

  - name: Extract Tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.96.tar.gz
      dest: /opt
      remote_src: True

  - name: Change permissions
    file:
      path: /opt/apache-tomcat-8.5.96/bin/startup.sh
      mode: 0777

  - name: Start tomcat
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.96/bin
